name: weather_app_flutter
description: "WeatherApp mobile: app meteo Flutter per Android."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/weatherapp-logo-cropped.png
    - assets/condizioni_atmosferiche/
    - assets/weather_icons/day/
    - assets/weather_icons/night/
